title:               Scott Taylor
description:         Ideas, essays, and projects
author:              Scott Taylor
include:             ['_pages']
exclude:             []
# You may need to change the base URL depending on your deploy configuration.
baseurl:             ''
url:                 'https://st.im'

# Use local timezone so weekday names in Fleeting Notes are correct
timezone: Europe/London

# Always publish posts with future dates
future: true

# Social settings
twitter_username:    ScottTaylor
github_username:     ScottTaylor
buttondown_username: scottmagic

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug
    source: newblog25
  topics:
    output: true
    permalink: /topics/:slug
  fleeting:
    output: true
    permalink: /fleeting/:name

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "newblog25/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_pages/**/*.md"
    values:
      layout: "page"
  - scope:
      path: "_topics/**/*.md"
    values:
      layout: "topic"
  - scope:
      path: "_fleeting/**/*.md"
    values:
      layout: "fleeting"
