[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"

# SPA routing for client-side router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
