[build]
  base = "hugo-site"
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.148.1"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"

# No SPA redirects; Hugo generates real pages
