baseURL = "https://example.com/"
languageCode = "en-us"
title = "Dario Amodei — Personal Site (Clone)"

# Hugo >=0.128: paginate deprecated -> use pagination.pagerSize
[pagination]
  pagerSize = 10

[params]
  description = "Bio, short posts, essays, research, op-eds, interviews."
  author = "Dario Amodei"

[permalinks]
  posts = "/posts/:slug/"
  essays = "/essays/:slug/"
  "op-eds" = "/op-eds/:slug/"
  interviews = "/interviews/:slug/"

[outputs]
  # Remove JSON home to avoid missing layout error
  home = ["HTML","RSS"]
  section = ["HTML","RSS"]
  page = ["HTML"]
