
import React from "react";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import ThemeToggle from "@/components/ThemeToggle";

const Index = () => {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <Helmet>
        <title>Scott Taylor — Personal Site</title>
        <meta name="description" content="Bio, short posts, essays, and thoughts by Scott Taylor. AI entrepreneur and co-founder of entourage." />
        <link rel="canonical" href={typeof window !== 'undefined' ? window.location.href : '/'} />
      </Helmet>

      <section className="container py-16 animate-fade-in">
        <div className="max-w-prose">
          <header className="mb-10 flex justify-between items-center">
            <div>
              <h1 className="h1">Scott Taylor</h1>
              <p className="sr-only">Personal site of Scott Taylor</p>
            </div>
            <ThemeToggle />
          </header>

          <article className="lead">
            <p>
              Scott Taylor is an AI entrepreneur and co-founder of <a className="link-underline" href="https://entourage.tech/" target="_blank" rel="noreferrer">entourage</a>, a network where agents continuously learn from each other's discoveries.
            </p>
            <p>
              Previously, Scott founded miDrive, an EdTech startup that raised ~$10m, bringing driver education into the digital age. He's passionate about building things from scratch and exploring the intersection of AI, collective intelligence, and human creativity.
            </p>
            <p>
              Scott writes about technology, AI, entrepreneurship, and the future of building things. He believes 2025 will be the year of builders who jump in with both feet, hack around, and build in public.
            </p>

            <section>
              <h2 className="h2">Recent thoughts</h2>
              <ul className="list">
                <li>
                  <Link className="link-underline" to="/posts/my-journey-to-co-founding-entourage">My journey to co-founding entourage</Link> <span className="small muted">(July 2025)</span>
                </li>
                <li>
                  <Link className="link-underline" to="/posts/jack-dorseys-bitchat-and-why-tinkering-matters">Jack Dorsey's bitchat and why tinkering matters</Link> <span className="small muted">(July 2025)</span>
                </li>
                <li>
                  <Link className="link-underline" to="/posts/ai-adhd">Anyone else got AI ADHD?</Link> <span className="small muted">(Jan 2025)</span>
                </li>
                <li>
                  <Link className="link-underline" to="/posts/you-can-just-build-things">You can just build things</Link> <span className="small muted">(Jan 2025)</span>
                </li>
                <li>
                  <Link className="link-underline" to="/posts/typography-demo">Typography and Style Demo</Link>
                </li>
              </ul>
            </section>

            <section>
              <h2 className="h2">Currently building</h2>
              <dl className="space-y-4">
                <div>
                  <dt className="font-medium">
                    <a className="link-underline" href="https://entourage.tech/" target="_blank" rel="noreferrer">entourage</a>
                  </dt>
                  <dd className="text-muted-foreground ml-0">
                    a network where agents continuously learn from each other's discoveries
                  </dd>
                </div>
                <div>
                  <dt className="font-medium">
                    <a className="link-underline" href="https://generatedlofi.com/" target="_blank" rel="noreferrer">generatedlofi</a>
                  </dt>
                  <dd className="text-muted-foreground ml-0">
                    a website generated by AI playing AI-generated lo-fi music
                  </dd>
                </div>
              </dl>
            </section>
          </article>
        </div>
      </section>
    </main>
  );
};

export default Index;
