name: Daily Fleeting Notes

on:
  schedule:
    # Run at 6:00 AM UTC every day
    - cron: '0 6 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  create-fleeting-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Create new fleeting note if needed
        run: |
          # Get today's date
          TODAY=$(date +%Y-%m-%d)
          FLEETING_DIR="_fleeting"
          FILE_PATH="${FLEETING_DIR}/${TODAY}.md"
          
          # Check if file already exists
          if [ -f "$FILE_PATH" ]; then
            echo "File $FILE_PATH already exists, no need to create it"
          else
            # Format the date for the title
            # Get day (without leading zero)
            DAY=$(date +%-d)
            
            # Get month name
            MONTH=$(date +%B)
            
            # Get year
            YEAR=$(date +%Y)
            
            # Get ordinal suffix for the day
            if [ $DAY -eq 1 ] || [ $DAY -eq 21 ] || [ $DAY -eq 31 ]; then
              SUFFIX="st"
            elif [ $DAY -eq 2 ] || [ $DAY -eq 22 ]; then
              SUFFIX="nd"
            elif [ $DAY -eq 3 ] || [ $DAY -eq 23 ]; then
              SUFFIX="rd"
            else
              SUFFIX="th"
            fi
            
            TITLE="${DAY}${SUFFIX} ${MONTH}, ${YEAR}"
            
            # Create the file content
            echo "---" > "$FILE_PATH"
            echo "date: ${TODAY} 12:00" >> "$FILE_PATH"
            echo "slug: \"${TODAY}\"" >> "$FILE_PATH"
            echo "title: \"${TITLE}\"" >> "$FILE_PATH"
            echo "layout: fleeting" >> "$FILE_PATH"
            echo "---" >> "$FILE_PATH"
            echo "" >> "$FILE_PATH"
            echo "Daily notes for ${TITLE}." >> "$FILE_PATH"
            
            echo "Created fleeting note for $TODAY"
            
            # Commit and push changes
            git add "$FILE_PATH"
            git commit -m "Add fleeting note for $TODAY"
            git push
          fi
          
      - name: Trigger Netlify build
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/681d86f9941c4c4e9bef4ede 